name: ViewingParty
version: "1.0"

main: fr.thegreensuits.viewing_party.Main

api: "1.18.2"
api-version: 1.18

commands:
  spawn:
    description: Se téléporter au point d'apparition
    usage: /<command>
    aliases: [hub, lobby]
  devmode:
    description: Activer le mode développeur
    usage: /<command>